# Site settings
title: CQMC Studios
header-img: img/home-bg.jpg
email: connorcleveland@gmail.com
description: "Video production company based in Houston, Texas."
baseurl: "/"
url: "http://cqmcstudios.com"
twitter_username: ConnorCleve
github_username:  connorcleve
facebook_username:  CQMCStudios

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
